config/routes.rb
Rails.application.routes.draw do
  resources :users
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/user.rb
class User < ApplicationRecord
  validates :name, :age, :gender, :email, presence: true
  validates :gender, inclusion: { in: %w[Male Female] }
  validates :email, uniqueness: true
  validates :age, numericality: { only_integer: true, greater_than_or_equal_to: 18 }
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: %i[show edit update destroy]

  # GET /users or /users.json
  def index
    @users = User.all
  end

  # GET /users/1 or /users/1.json
  def show; end

  # GET /users/new
  def new
    @user = User.new
  end

  # GET /users/1/edit
  def edit; end

  # POST /users or /users.json
  def create
    @user = User.new(user_params)

    respond_to do |format|
      if @user.save
        format.html { redirect_to user_url(@user), notice: 'User was successfully created.' }
        format.json { render :show, status: :created, location: @user }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /users/1 or /users/1.json
  def update
    respond_to do |format|
      if @user.update(user_params)
        format.html { redirect_to user_url(@user), notice: 'User was successfully updated.' }
        format.json { render :show, status: :ok, location: @user }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /users/1 or /users/1.json
  def destroy
    @user.destroy

    respond_to do |format|
      format.html { redirect_to users_url, notice: 'User was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_user
    @user = User.find(params[:id])
  end

  # Only allow a list of trusted parameters through.
  def user_params
    params.require(:user).permit(:name, :age, :gender, :email)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>CrudDemo</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossorigin="anonymous">
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-ka7Sk0Gln4gmtz2MlQnikT1wXgYsOg+OMhuP+IlRH9sENBO0LRn5q+8nbTov4+1p" crossorigin="anonymous"></script>
  </head>
  <body>
    <main class="container mt-2">
      <%= yield %>
    </main>
  </body>
</html>

app/views/users/_form.html.erb
<%= form_with(model: user,class:"card") do |form| %>
  <div class="card-body">
    <% if user.errors.any? %>
      <div style="color: red">
        <h2><%= pluralize(user.errors.count, "Error") %></h2>
        <% user.errors.each do |error| %>
          <div class="alert alert-warning" role="alert"><%= error.full_message %></div>
        <% end %>
      </div>
    <% end %>
    <div class="mb-3">
      <%= form.label :name,class:"form-label" %>
      <%= form.text_field :name ,class:"form-control" %>
    </div>
    <div class="mb-3">
      <%= form.label :age , class:"form-label" %>
      <%= form.number_field :age,class:"form-control" %>
    </div>
    <div class="mb-3">
      <%= form.label :gender,class:"form-label" %>
      <%= form.text_field :gender,class:"form-control" %>
    </div>
    <div class="mb-3">
      <%= form.label :email ,class:"form-label" %>
      <%= form.text_field :email,class:"form-control" %>
    </div>
    <div class="mb-3">
      <%= form.submit class: "btn btn-primary" %>
      <%= link_to "Back to users", users_path,class:"btn btn-secondary" %>
    </div>
  </div>
<% end %>

app/views/users/_user.html.erb
<div id="<%= dom_id user %>" class="card">
  <ul class="list-group list-group-flush">
    <li class="list-group-item">
      <strong>Name:</strong>
      <%= user.name %>
    </li>
    <li class="list-group-item">
      <strong>Age:</strong>
      <%= user.age %>
    </li>
    <li class="list-group-item">
      <strong>Gender:</strong>
      <%= user.gender %>
    </li>
    <li class="list-group-item">
      <strong>Email:</strong>
      <%= user.email %>
    </li>
  </ul>
</div>

app/views/users/edit.html.erb
<h1>Editing User</h1>
<%= render "form", user: @user %>

app/views/users/index.html.erb
<% if !notice.nil? %>
  <div class="alert alert-success"><%= notice %></div>
<% end %>
<h1 class="text-center">Users</h1>
<table id="users" class="table table-bordered table-hover table-dark table-striped">
  <thead>
    <tr>
      <th>Name</th>
      <th>Age</th>
      <th>Gender</th>
      <th>Email</th>
      <th>Actions</th>
    </tr>
  </thead>
  <tbody>
    <% @users.each do |user| %>
      <tr>
        <td><%=user.name %></td>
        <td><%=user.age %></td>
        <td><%=user.gender %></td>
        <td><%=user.email %></td>
        <td> <%= link_to "Show", user %></td>
      </tr>
    <% end %>
  </tbody>
</table>
<%= link_to "New user", new_user_path,class:"btn btn-primary" %>

app/views/users/new.html.erb
<h1 class="text-center">New User</h1>
<%= render "form", user: @user %>

app/views/users/show.html.erb
<% if !notice.nil? %>
  <div class="alert alert-success"><%= notice %></div>
<% end %>
<%= render @user %>
<br>
<div>
  <%= link_to "Edit", edit_user_path(@user) ,class:"btn btn-success"%>
  <%= link_to "Back to users", users_path ,class:"btn btn-secondary"%>
  <%= button_to "Delete", @user, method: :delete ,class:"btn btn-danger mt-2"%>
</div>